// Build dist/, the @vendra/design-system package a tenant storefront installs: ES-module
// components (React is a peer dependency) with their types, one stylesheet with its fonts,
// the tenant theme files and the theme API. Plain scripts in components/ (window globals
// for the storefront templates) are left out: only files with exports are published.
const fs = require('node:fs');
const path = require('node:path');
const {transformSync, parseSync} = require('rolldown/experimental');
const {sources} = require('./components.cjs');

const repo = path.resolve(__dirname, '../..');
const dist = path.join(repo, 'dist');
const HEADER = '// GENERATED by npm --prefix templates run build. Edit the sources, not dist/.\n';

const read = file => fs.readFileSync(path.join(repo, file), 'utf8');
const isModule = file =>
  parseSync(file, read(file)).program.body.some(node => node.type === 'ExportNamedDeclaration');

// components/x/Y.jsx → {path: 'components/x/Y.js', code}. Relative .jsx imports become .js;
// React components get 'use client' so server-rendered apps (Next.js) load them as client modules.
function esm(file) {
  const {code, errors} = transformSync(file, read(file), {jsx: {runtime: 'classic'}});
  if (errors.length) throw new Error(file + ': ' + errors.map(e => e.message).join('; '));
  let out = code;
  const imports = parseSync(file, code).program.body.filter(
    node => node.type === 'ImportDeclaration' && node.source.value.endsWith('.jsx')
  );
  for (const node of imports.sort((a, b) => b.source.start - a.source.start)) {
    out =
      out.slice(0, node.source.start) +
      JSON.stringify(node.source.value.replace(/\.jsx$/, '.js')) +
      out.slice(node.source.end);
  }
  return (file.endsWith('.jsx') ? "'use client';\n" : '') + HEADER + out;
}

// Hand-written declarations use React's global types; published ones import them.
function declarations(file) {
  const dts = file.replace(/\.jsx?$/, '.d.ts');
  if (!fs.existsSync(path.join(repo, dts)))
    throw new Error(file + ' exports but has no ' + path.basename(dts));
  const text = read(dts).replace(/\bJSX\.Element\b/g, 'React.JSX.Element');
  return (/\bReact\./.test(text) ? "import * as React from 'react';\n" : '') + text;
}

// styles.css with its @imports inlined, fonts next to it.
function stylesheet(file, seen = new Set()) {
  if (seen.has(file)) return '';
  seen.add(file);
  return read(file)
    .replace(/@import url\('([^']+)'\);\n?/g, (_, href) => {
      const child = path.posix.join(path.posix.dirname(file), href);
      return '/* ' + child + ' */\n' + stylesheet(child, seen) + '\n';
    })
    .replace(/url\('\.\.\/assets\/fonts\/([^']+)'\)/g, "url('./fonts/$1')");
}

// Map of path inside dist/ → string or Buffer.
function packageFiles() {
  const files = new Map();
  const modules = sources(repo).filter(isModule);
  for (const file of modules) {
    const out = file.replace(/\.jsx?$/, '');
    files.set(out + '.js', esm(file));
    files.set(out + '.d.ts', declarations(file));
  }
  const entries = modules.map(file => './' + file.replace(/\.jsx?$/, '.js'));
  files.set('index.js', HEADER + entries.map(entry => "export * from '" + entry + "';\n").join(''));
  files.set('index.d.ts', entries.map(entry => "export * from '" + entry + "';\n").join(''));

  const css = stylesheet('styles.css');
  const fonts = [...css.matchAll(/url\('\.\/fonts\/([^']+)'\)/g)].map(match => match[1]);
  files.set(
    'styles.css',
    '/* GENERATED from styles.css by npm --prefix templates run build: tokens, base styles and every ag-* component class. */\n' +
      css
  );
  for (const font of new Set(fonts))
    files.set('fonts/' + font, fs.readFileSync(path.join(repo, 'assets/fonts', font)));

  const tenants = fs
    .readdirSync(path.join(repo, 'tokens/tenants'))
    .filter(name => name.endsWith('.css'))
    .sort();
  for (const name of tenants) files.set('tenants/' + name, read('tokens/tenants/' + name));
  files.set('tenants.css', read('tokens/tenants.css'));

  const theme = read('templates/_shared/tenant-theme.js');
  files.set('theme.cjs', HEADER + theme);
  files.set(
    'theme.js',
    HEADER +
      "import theme from './theme.cjs';\n" +
      'export const {VENDRA, CHOICES, FONTS, validate, checks, tokens, contrast, oklch, fromOklch, css, tenantCss, email} = theme;\n'
  );
  files.set('theme.d.ts', read('templates/_shared/tenant-theme.d.ts'));
  files.set('theme.d.cts', read('templates/_shared/tenant-theme.d.ts'));
  return files;
}

function listed(folder, prefix = '') {
  if (!fs.existsSync(folder)) return [];
  return fs
    .readdirSync(folder, {withFileTypes: true})
    .flatMap(entry =>
      entry.isDirectory()
        ? listed(path.join(folder, entry.name), prefix + entry.name + '/')
        : [prefix + entry.name]
    );
}

// Writes dist/ (or, with check, throws when it differs). Returns the number of files changed.
function buildPackage(check) {
  const files = packageFiles();
  let changed = 0;
  for (const [name, content] of files) {
    const target = path.join(dist, name);
    const current = fs.existsSync(target) ? fs.readFileSync(target) : null;
    if (current && Buffer.from(content).equals(current)) continue;
    if (check) throw new Error('dist/' + name + ' is stale. Run npm --prefix templates run build.');
    fs.mkdirSync(path.dirname(target), {recursive: true});
    fs.writeFileSync(target, content);
    changed++;
  }
  for (const name of listed(dist).filter(name => !files.has(name))) {
    if (check)
      throw new Error('dist/' + name + ' has no source. Run npm --prefix templates run build.');
    fs.rmSync(path.join(dist, name));
    changed++;
  }
  if (!check) removeEmptyFolders(dist);
  return changed;
}

function removeEmptyFolders(folder) {
  for (const entry of fs.readdirSync(folder, {withFileTypes: true}))
    if (entry.isDirectory()) removeEmptyFolders(path.join(folder, entry.name));
  if (folder !== dist && !fs.readdirSync(folder).length) fs.rmdirSync(folder);
}

module.exports = {buildPackage, packageFiles, dist};
