// Bilingual bag copy. Edit here, then run npm --prefix templates run build.
// Formatting helpers keep delivery fees and tenant-specific store details current.
function vfCopy(S) {
  const C = {
    en: {
      steps: 'Checkout steps',
      s1: 'Bag',
      s2: 'Payment',
      s3: 'Done',
      titleA: 'Your',
      titleB: 'bag.',
      remove: 'Remove',
      dec: 'Fewer',
      inc: 'More',
      delivery: 'Delivery',
      name: 'Recipient name',
      phone: 'Recipient phone',
      zone: 'Delivery zone',
      saved: 'Send to a saved address',
      address2: 'Plaque, unit and floor',
      addressHint: 'Anything the map can’t show, like the name on the bell.',
      addressFull: 'Full address',
      pin: 'Delivery location',
      mapFailed: 'The map didn’t load. Write the full address and we’ll call to confirm it.',
      day: 'Delivery day',
      soldOut: 'Sold out',
      pastCutoff: 'Order by {time}',
      slot: 'Time slot',
      card: 'Card message',
      cardHint: 'We write every card by hand. Up to 200 characters.',
      summary: 'Order summary',
      sub: 'Subtotal',
      fee: 'Delivery',
      total: 'Total',
      free: 'Free',
      next: 'Continue to payment',
      payNote: 'Card-to-card payment on the next step. No card details are stored.',
      promo: 'Promo code',
      apply: 'Apply',
      promoUnknown: 'We don’t recognise that code.',
      promoMin: 'This code needs a subtotal of {min}.',
      promoOn: '{code} · {percent}% off',
      promoPaused: '{code} needs a subtotal of {min}.',
      removePromo: 'Remove code',
      emptyA: 'Your bag is empty',
      emptyB: '— for now.',
      emptyP: 'Seasonal bouquets are hand-tied each morning.',
      keep: 'Keep browsing',
      labels: {
        each: 'Each: '
      },
      errors: {
        name: 'Enter the recipient’s name.',
        phone: 'Enter an 11-digit mobile number starting with 09.',
        location: 'Place the pin on the delivery address.',
        address: 'Add the plaque and unit, or the house number.',
        addressFull: 'Enter a full address (at least 6 characters).'
      }
    },
    fa: {
      steps: 'مراحل خرید',
      s1: 'سبد',
      s2: 'پرداخت',
      s3: 'پایان',
      titleA: 'سبد',
      titleB: 'شما.',
      remove: 'حذف',
      dec: 'کمتر',
      inc: 'بیشتر',
      delivery: 'ارسال',
      name: 'نام گیرنده',
      phone: 'موبایل گیرنده',
      zone: 'محدوده ارسال',
      saved: 'ارسال به نشانی ذخیره‌شده',
      address2: 'پلاک، واحد و طبقه',
      addressHint: 'هر چیزی که روی نقشه دیده نمی‌شود، مثل نام روی زنگ.',
      addressFull: 'آدرس کامل',
      pin: 'محل تحویل',
      mapFailed: 'نقشه بارگذاری نشد. آدرس کامل را بنویسید؛ برای تأیید تماس می‌گیریم.',
      day: 'روز ارسال',
      soldOut: 'تکمیل',
      pastCutoff: 'سفارش تا {time}',
      slot: 'بازه زمانی',
      card: 'متن کارت',
      cardHint: 'همه کارت‌ها را با دست می‌نویسیم. تا ۲۰۰ نویسه.',
      summary: 'خلاصه سفارش',
      sub: 'جمع جزء',
      fee: 'هزینه ارسال',
      total: 'جمع کل',
      free: 'رایگان',
      next: 'ادامه و پرداخت',
      payNote: 'پرداخت کارت‌به‌کارت در مرحله بعد. اطلاعات کارت ذخیره نمی‌شود.',
      promo: 'کد تخفیف',
      apply: 'اعمال',
      promoUnknown: 'این کد معتبر نیست.',
      promoMin: 'این کد برای جمع خرید از {min} به بالاست.',
      promoOn: '{code} · {percent}٪ تخفیف',
      promoPaused: '{code} برای جمع خرید از {min} به بالاست.',
      removePromo: 'حذف کد',
      emptyA: 'سبد شما خالی است',
      emptyB: '— فعلاً.',
      emptyP: 'دسته‌گل‌های فصلی هر صبح با دست بسته می‌شوند.',
      keep: 'ادامه خرید',
      labels: {
        each: 'هر عدد: '
      },
      errors: {
        name: 'نام گیرنده را وارد کنید.',
        phone: 'شماره موبایل ۱۱ رقمی با ۰۹ وارد کنید.',
        location: 'سوزن را روی محل تحویل بگذارید.',
        address: 'پلاک و واحد یا شماره خانه را بنویسید.',
        addressFull: 'آدرس کامل را وارد کنید؛ دست‌کم ۶ نویسه.'
      }
    }
  }[S.lang];
  return {...VF_PIN_COPY[S.lang], ...C};
}
