// Bilingual bag copy. Edit here, then run npm --prefix templates run build.
// Formatting helpers keep delivery fees and tenant-specific store details current.
function vfCopy(S) {
  const C = {
    en: {
      steps: 'Checkout steps',
      s1: 'Bag',
      s2: 'Delivery',
      s3: 'Payment',
      s4: 'Done',
      doneStep: '(completed)',
      caption: 'Step {n} of {total} · {label}',
      titleA: 'Your',
      titleB: 'bag.',
      deliveryA: 'Delivery',
      deliveryB: 'details.',
      toDelivery: 'Continue to delivery',
      backToBag: 'Back to bag',
      errorTitle: 'Check {count} details to continue.',
      recipient: 'Recipient',
      when: 'When',
      you: 'Your details',
      youHint: 'We’ll text you order updates and a photo of the flowers before they leave the studio.',
      sender: 'Your name',
      senderPhone: 'Your mobile',
      zonePending: 'Place the pin to see the zone and delivery fee.',
      zoneSet: 'Set from the pin. ',
      slotClosed: 'Closed',
      cards: 'Cards',
      cardsIntro: 'Add a handwritten card to any item.',
      cardFor: 'Card for {name}',
      cardNext: 'You’ll write the card message in the next step.',
      addCard: 'Add a card · +{price}',
      addCardLabel: 'Add a card · +{price}, for {name}',
      remove: 'Remove',
      dec: 'Fewer',
      inc: 'More',
      delivery: 'Delivery',
      name: 'Recipient name',
      phone: 'Recipient phone',
      zone: 'Delivery zone',
      saved: 'Send to a saved address',
      address2: 'Plaque, unit and floor',
      addressHint: 'Anything the map can’t show, like the name on the bell.',
      addressFull: 'Full address',
      pin: 'Delivery location',
      mapFailed: 'The map didn’t load. Write the full address and we’ll call to confirm it.',
      day: 'Delivery day',
      soldOut: 'Sold out',
      pastCutoff: 'Order by {time}',
      slot: 'Time slot',
      cardHint: 'We write every card by hand. Up to 200 characters.',
      summary: 'Order summary',
      sub: 'Subtotal',
      fee: 'Delivery',
      total: 'Total',
      free: 'Free',
      next: 'Continue to payment',
      payNote: 'Card-to-card payment on the next step. No card details are stored.',
      promo: 'Promo code',
      apply: 'Apply',
      promoUnknown: 'We don’t recognise that code.',
      promoMin: 'This code needs a subtotal of {min}.',
      promoOn: '{code} · {percent}% off',
      promoPaused: '{code} needs a subtotal of {min}.',
      removePromo: 'Remove code',
      emptyA: 'Your bag is empty',
      emptyB: '— for now.',
      emptyP: 'Seasonal bouquets are hand-tied each morning.',
      keep: 'Keep browsing',
      labels: {
        each: 'Each: '
      },
      errors: {
        name: 'Enter the recipient’s name.',
        phone: 'Enter an 11-digit mobile number starting with 09.',
        location: 'Place the pin on the delivery address.',
        outside: 'We don’t deliver there yet. Move the pin inside Karaj, Alborz or Tehran.',
        address: 'Add the plaque and unit, or the house number.',
        addressFull: 'Enter a full address (at least 6 characters).',
        card: 'Write what the card should say.',
        sender: 'Enter your name.',
        senderPhone: 'Enter your 11-digit mobile number starting with 09.'
      }
    },
    fa: {
      steps: 'مراحل خرید',
      s1: 'سبد',
      s2: 'ارسال',
      s3: 'پرداخت',
      s4: 'پایان',
      doneStep: '(انجام شد)',
      caption: 'مرحله {n} از {total} · {label}',
      titleA: 'سبد',
      titleB: 'شما.',
      deliveryA: 'جزئیات',
      deliveryB: 'ارسال.',
      toDelivery: 'ادامه و ارسال',
      backToBag: 'بازگشت به سبد',
      errorTitle: '{count} مورد را بررسی کنید تا ادامه دهید.',
      recipient: 'گیرنده',
      when: 'زمان',
      you: 'مشخصات شما',
      youHint: 'وضعیت سفارش و عکس گل‌ها را پیش از ارسال از استودیو برایتان پیامک می‌کنیم.',
      sender: 'نام شما',
      senderPhone: 'موبایل شما',
      zonePending: 'سوزن را بگذارید تا محدوده و هزینه ارسال را ببینید.',
      zoneSet: 'بر اساس سوزن روی نقشه. ',
      slotClosed: 'بسته',
      cards: 'کارت‌ها',
      cardsIntro: 'به هر کدام از سفارش‌ها می‌توانید کارت دست‌نویس اضافه کنید.',
      cardFor: 'کارت برای {name}',
      cardNext: 'متن کارت را در مرحله بعد می‌نویسید.',
      addCard: 'افزودن کارت · +{price}',
      addCardLabel: 'افزودن کارت · +{price}، برای {name}',
      remove: 'حذف',
      dec: 'کمتر',
      inc: 'بیشتر',
      delivery: 'ارسال',
      name: 'نام گیرنده',
      phone: 'موبایل گیرنده',
      zone: 'محدوده ارسال',
      saved: 'ارسال به نشانی ذخیره‌شده',
      address2: 'پلاک، واحد و طبقه',
      addressHint: 'هر چیزی که روی نقشه دیده نمی‌شود، مثل نام روی زنگ.',
      addressFull: 'آدرس کامل',
      pin: 'محل تحویل',
      mapFailed: 'نقشه بارگذاری نشد. آدرس کامل را بنویسید؛ برای تأیید تماس می‌گیریم.',
      day: 'روز ارسال',
      soldOut: 'تکمیل',
      pastCutoff: 'سفارش تا {time}',
      slot: 'بازه زمانی',
      cardHint: 'همه کارت‌ها را با دست می‌نویسیم. تا ۲۰۰ نویسه.',
      summary: 'خلاصه سفارش',
      sub: 'جمع جزء',
      fee: 'هزینه ارسال',
      total: 'جمع کل',
      free: 'رایگان',
      next: 'ادامه و پرداخت',
      payNote: 'پرداخت کارت‌به‌کارت در مرحله بعد. اطلاعات کارت ذخیره نمی‌شود.',
      promo: 'کد تخفیف',
      apply: 'اعمال',
      promoUnknown: 'این کد معتبر نیست.',
      promoMin: 'این کد برای جمع خرید از {min} به بالاست.',
      promoOn: '{code} · {percent}٪ تخفیف',
      promoPaused: '{code} برای جمع خرید از {min} به بالاست.',
      removePromo: 'حذف کد',
      emptyA: 'سبد شما خالی است',
      emptyB: '— فعلاً.',
      emptyP: 'دسته‌گل‌های فصلی هر صبح با دست بسته می‌شوند.',
      keep: 'ادامه خرید',
      labels: {
        each: 'هر عدد: '
      },
      errors: {
        name: 'نام گیرنده را وارد کنید.',
        phone: 'شماره موبایل ۱۱ رقمی با ۰۹ وارد کنید.',
        location: 'سوزن را روی محل تحویل بگذارید.',
        outside: 'هنوز به این نقطه ارسال نداریم. سوزن را در کرج، البرز یا تهران بگذارید.',
        address: 'پلاک و واحد یا شماره خانه را بنویسید.',
        addressFull: 'آدرس کامل را وارد کنید؛ دست‌کم ۶ نویسه.',
        card: 'متن کارت را بنویسید.',
        sender: 'نام خود را وارد کنید.',
        senderPhone: 'شماره موبایل ۱۱ رقمی خود را با ۰۹ وارد کنید.'
      }
    }
  }[S.lang];
  return {...VF_PIN_COPY[S.lang], ...C};
}
